

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: loja
          uri: http://localhost:8080
          predicates:
            - Path=/loja/**
        - id: fornecedor
          uri: http://localhost:8081
          predicates:
            - Path=/fornecedor/**
        - id: transportador
          uri: http://localhost:8083
          predicates:
            - Path=/transportador/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
  port: 5555

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: "*"